### ISSUE TITLE
nghttp2 implementation using FFI

### ISSUE THREAD

**Issue by kelunik** [amphp/hpack#6]
PHP 7.4 offers FFI, so we can build the huffman decoding using nghttp2 and FFI if both are available on the given system and otherwise fall back to our current implementation.

**Comment by bwoebi** [comment]
Sounds reasonable - though you probably should measure the FFI overhead for small inputs and check whether our userland or the FFI impl is faster (i.e. for input sizes of around ~200 bytes).

**Comment by kelunik** [comment]
If there's only a slight overhead, I'd still prefer an FFI implementation, because the current implementation needs about 30 MB of RAM.

**Comment by kelunik** [comment]
I have started working on an implementation locally.

**Comment by kelunik** [comment]
I have a working implementation locally now and the initial test with the included script shows some speed up.
